import {
  DEFAULT_RW0_DATABASE_PATH,
  RECOVERY_V0_SIGNAL_VERSION,
  RW0_CHECKPOINT,
  RW0_COOLDOWN_MS,
  RW0_COST_MODEL,
  RW0_DISCOVERY_CALLS_PER_SCREENING_CYCLE,
  RW0_EXECUTION_MODEL,
  RW0_EXIT_SPEC_VERSION,
  RW0_MAX_CONCURRENT_WATCHES,
  RW0_MAX_EPISODES_PER_MINT_PER_24H,
  RW0_NETWORK_TIMEOUT_MS,
  RW0_SCHEDULING_POLICY,
  RW0_SCHEMA_VERSION,
  RW0_SAFETY_SPEC_VERSION,
  RW0_SCREENING_DISPOSITIONS,
  RW0_SCREENING_FETCH_CONCURRENCY,
  RW0_SCREENING_MAX_CANDIDATES,
  RW0_SCREENING_WALL_BUDGET_MS,
  RW0_SHADOW_PAPER_SPEC_VERSION,
  RW0_SPEC_NAME,
  RW0_SPEC_VERSION,
  RW0_WATCH_CADENCE_MS,
  RW0_WATCH_FETCH_CONCURRENCY,
  RW0_WATCH_SLOT_STATES,
  RW0_WATCH_TTL_MS,
} from './constants.js';
import {
  RECOVERY_V0_SIGNAL_FINGERPRINT,
  RW0_EXIT_FINGERPRINT,
  RW0_SHADOW_PAPER_FINGERPRINT,
  RW0_WATCHER_DEFINITION_FINGERPRINT,
  RW0_SAFETY_SPEC_FINGERPRINT,
} from './identity.js';
import { recoveryMigrationSqlDigest } from './db/migrations.js';
import { sanitizeRecoveryDatabasePathDisplay } from './sanitizer.js';
import type { RecoveryCycleMetrics, RecoveryWatcherConfig } from './types.js';

export function formatRecoveryStatusLines(config: RecoveryWatcherConfig): string[] {
  return [
    'RECOVERY WATCHER',
    `Checkpoint: ${RW0_CHECKPOINT}`,
    `Spec: ${RW0_SPEC_VERSION}`,
    `Name: ${RW0_SPEC_NAME}`,
    `Watcher fingerprint: ${RW0_WATCHER_DEFINITION_FINGERPRINT}`,
    `Signal: ${RECOVERY_V0_SIGNAL_VERSION}`,
    `Signal fingerprint: ${RECOVERY_V0_SIGNAL_FINGERPRINT}`,
    `Safety spec: ${RW0_SAFETY_SPEC_VERSION}`,
    `Safety fingerprint: ${RW0_SAFETY_SPEC_FINGERPRINT}`,
    `Shadow paper spec: ${RW0_SHADOW_PAPER_SPEC_VERSION}`,
    `Shadow paper fingerprint: ${RW0_SHADOW_PAPER_FINGERPRINT}`,
    `Exit spec: ${RW0_EXIT_SPEC_VERSION}`,
    `Exit fingerprint: ${RW0_EXIT_FINGERPRINT}`,
    `Recovery migration digest: ${recoveryMigrationSqlDigest(RW0_SCHEMA_VERSION)}`,
    'Mode: PAPER / DATA RESEARCH ONLY',
    'Automatic live trading: UNAVAILABLE',
    'Signer: NONE',
    'Wallet: NONE',
    'Broadcast: NONE',
    `TRADING_ENABLED: ${config.tradingEnabled ? 'true' : 'false'}`,
    `LIVE_BROADCAST_ENABLED: ${config.liveBroadcastEnabled ? 'true' : 'false'}`,
    `Intended recovery DB path: ${sanitizeRecoveryDatabasePathDisplay(config.databasePath)}`,
    `Default recovery DB path: ${sanitizeRecoveryDatabasePathDisplay(DEFAULT_RW0_DATABASE_PATH)}`,
    `Configured production DB path: ${sanitizeRecoveryDatabasePathDisplay(config.configuredProductionDatabasePath)}`,
    `Recovery schema version: ${String(RW0_SCHEMA_VERSION)}`,
    'Production schema: untouched (must remain 9; migration 010 ABSENT)',
    `Watch cadence ms: ${String(RW0_WATCH_CADENCE_MS)}`,
    `Watch TTL ms: ${String(RW0_WATCH_TTL_MS)}`,
    `Cooldown ms: ${String(RW0_COOLDOWN_MS)}`,
    `Max concurrent high-res watch slots: ${String(RW0_MAX_CONCURRENT_WATCHES)}`,
    `Watch slot states: ${RW0_WATCH_SLOT_STATES.join(', ')}`,
    `Max episodes per mint per 24h: ${String(RW0_MAX_EPISODES_PER_MINT_PER_24H)}`,
    `Cost model: ${RW0_COST_MODEL}`,
    `Execution model: ${RW0_EXECUTION_MODEL}`,
    'Shadow research: SHADOW_RESEARCH_OPEN is the only simulation path (safety_incomplete, completeness FAIL, not live-readiness)',
    'Shadow exit/CLOSED: NOT IMPLEMENTED; SHADOW_RESEARCH_OPEN cannot CLOSED until a dedicated exit slice',
    'Recovery confirmation: legal only when recoveryConfirmedAt < watchStartedAt + 2h TTL; exact expiry belongs to EXPIRED',
    'Confirmation persist: derived from a stored rw0_market_observations row; caller economics cannot override',
    'Safety-approved paper: PAPER_ELIGIBLE / PAPER_OPEN names are reserved and unreachable in rw0_v3',
    'Safety decisions are reduced from canonical persisted evidence only; caller-supplied gate status cannot reach PAPER',
    'Token-rights, holder, bundle, and creator evidence: persisted PASS/FAIL/UNKNOWN with fail-closed reduction',
    'Runtime RW0_DATABASE_PATH=:memory: REJECTED; :memory: is test-only via openRecoveryMemoryDatabase',
    'Holder gate: largest aggregated nonexcluded owner <=10%; top-20-only and incomplete coverage cannot PASS',
    'Bundle gate: complete linked cluster <=20%; heuristic cluster is not ownership and incomplete graph is UNKNOWN',
    'Creator gate: missing trustworthy identity is UNKNOWN; no identity guessing',
    'Discovery coverage: INCOMPLETE (DexScreener latest profile/boost research collection only)',
    'Historical recovery_v0 sample used sparse ~5-minute observations; 60s confirmation is a new forward regime and historical percentages are not proof of that regime',
    'Slice 3A: persisted safety evidence and safety rejection only; no paper position',
    'Networked forward observation: IMPLEMENTED (screening independent of episodes; NOT_DIP does not create an episode or start cooldown)',
    `Scheduling: ${RW0_SCHEDULING_POLICY} (watch due target from pass start; sleep max(0, next_due - monotonic_now); one overdue pass only, no catch-up storm, no overlapping cycles, no Math.random jitter)`,
    'Watch work has priority over optional leftover-budget screening',
    `Watch fetch concurrency: ${String(RW0_WATCH_FETCH_CONCURRENCY)} (bounded; persist serial in episode_id order)`,
    `Screening fetch concurrency: ${String(RW0_SCREENING_FETCH_CONCURRENCY)}`,
    `Screening wall-time budget ms: ${String(RW0_SCREENING_WALL_BUDGET_MS)} (also clipped to time remaining until the next watch due)`,
    `Discovery calls per screening cycle: ${String(RW0_DISCOVERY_CALLS_PER_SCREENING_CYCLE)} (profile + boost, concurrent)`,
    `Screening candidate enrichment cap: ${String(RW0_SCREENING_MAX_CANDIDATES)}`,
    `Network timeout ms: ${String(RW0_NETWORK_TIMEOUT_MS)}`,
    'No provider retry storm; known MarketDataError/DiscoveryError fail that tick; unknown TypeError/integrity errors are fatal',
    `Screening dispositions: ${RW0_SCREENING_DISPOSITIONS.join(', ')}`,
    'dip_filter_result is separate from operational disposition: PASS can still be WATCH_CAP_FULL/EPISODE_LIMIT/COOLDOWN',
    'Pinned pair never switches after dip admission; exact-pair miss does not fall back to best pair',
    'Confirmation binds SIGNAL_PENDING_SAFETY to a persisted rw0_market_observations row; safety rejection reads persisted evidence',
    'Slice 3A does not open SHADOW_RESEARCH_OPEN, PAPER_ELIGIBLE, PAPER_OPEN, or CLOSED',
    'collectedAt is this process local collection time, not token launch or exchange trade time',
    'DexScreener does not expose a trustworthy quote/trade timestamp through the existing adapter; none is invented',
    'Provider cap is not a claim of exact external DexScreener rate-limit safety',
    'Prior bounded public one-cycle DexScreener smoke is disposable engineering smoke only; excluded from strategy forward-validation; do not merge that DB',
    'After this Slice-2 repair is approved, the first retained forward run freezes watcher fingerprint and schema digest for that dataset; do not run another public smoke until the repair is reviewed',
  ];
}

export function formatRecoveryCycleLines(metrics: RecoveryCycleMetrics): string[] {
  return [
    `Recovery cycle at ${metrics.at}`,
    `Discovery calls: ${String(metrics.discoveryCalls)} failures=${String(metrics.discoveryFailures)}`,
    `Candidates discovered=${String(metrics.candidatesDiscovered)} deduped=${String(metrics.candidatesDeduped)} selected=${String(metrics.candidatesSelected)} skipped_cap=${String(metrics.candidatesSkippedCap)} enriched=${String(metrics.candidatesEnriched)} enrichment_failed=${String(metrics.candidatesEnrichmentFailed)}`,
    `Active watches at start: ${String(metrics.activeWatchesAtStart)}`,
    `Market fetches success=${String(metrics.marketFetchSuccesses)} fail=${String(metrics.marketFetchFailures)} provider_failures=${String(metrics.providerFailures)}`,
    `Confirmations=${String(metrics.confirmations)} expiries=${String(metrics.expiries)} rejected_safety_unknown=${String(metrics.rejectedSafetyUnknown)}`,
    `Dip filter PASS (including capacity-blocked dips): ${String(metrics.dipFilterPassCount)}`,
    `Screening skipped budget=${String(metrics.candidatesSkippedBudget)} budget_exhausted=${metrics.screeningBudgetExhausted ? 'true' : 'false'}`,
    `Screening dispositions: ${RW0_SCREENING_DISPOSITIONS.map((disposition) => `${disposition}=${String(metrics.screeningByDisposition[disposition])}`).join(' ')}`,
  ];
}
