import {
  DEFAULT_RW0_DATABASE_PATH,
  RECOVERY_V0_SIGNAL_VERSION,
  RW0_CHECKPOINT,
  RW0_COOLDOWN_MS,
  RW0_COST_MODEL,
  RW0_EXECUTION_MODEL,
  RW0_EXIT_SPEC_VERSION,
  RW0_MAX_CONCURRENT_WATCHES,
  RW0_MAX_EPISODES_PER_MINT_PER_24H,
  RW0_SCHEMA_VERSION,
  RW0_SHADOW_PAPER_SPEC_VERSION,
  RW0_SPEC_NAME,
  RW0_SPEC_VERSION,
  RW0_WATCH_CADENCE_MS,
  RW0_WATCH_SLOT_STATES,
  RW0_WATCH_TTL_MS,
} from './constants.js';
import {
  RECOVERY_V0_SIGNAL_FINGERPRINT,
  RW0_EXIT_FINGERPRINT,
  RW0_SHADOW_PAPER_FINGERPRINT,
  RW0_WATCHER_DEFINITION_FINGERPRINT,
} from './identity.js';
import { recoveryMigrationSqlDigest } from './db/migrations.js';
import { sanitizeRecoveryDatabasePathDisplay } from './sanitizer.js';
import type { RecoveryWatcherConfig } from './types.js';

export function formatRecoveryStatusLines(config: RecoveryWatcherConfig): string[] {
  return [
    'RECOVERY WATCHER',
    `Checkpoint: ${RW0_CHECKPOINT}`,
    `Spec: ${RW0_SPEC_VERSION}`,
    `Name: ${RW0_SPEC_NAME}`,
    `Watcher fingerprint: ${RW0_WATCHER_DEFINITION_FINGERPRINT}`,
    `Signal: ${RECOVERY_V0_SIGNAL_VERSION}`,
    `Signal fingerprint: ${RECOVERY_V0_SIGNAL_FINGERPRINT}`,
    `Shadow paper spec: ${RW0_SHADOW_PAPER_SPEC_VERSION}`,
    `Shadow paper fingerprint: ${RW0_SHADOW_PAPER_FINGERPRINT}`,
    `Exit spec: ${RW0_EXIT_SPEC_VERSION}`,
    `Exit fingerprint: ${RW0_EXIT_FINGERPRINT}`,
    `Recovery migration digest: ${recoveryMigrationSqlDigest(RW0_SCHEMA_VERSION)}`,
    'Mode: PAPER / DATA RESEARCH ONLY',
    'Automatic live trading: UNAVAILABLE',
    'Signer: NONE',
    'Wallet: NONE',
    'Broadcast: NONE',
    `TRADING_ENABLED: ${config.tradingEnabled ? 'true' : 'false'}`,
    `LIVE_BROADCAST_ENABLED: ${config.liveBroadcastEnabled ? 'true' : 'false'}`,
    `Intended recovery DB path: ${sanitizeRecoveryDatabasePathDisplay(config.databasePath)}`,
    `Default recovery DB path: ${sanitizeRecoveryDatabasePathDisplay(DEFAULT_RW0_DATABASE_PATH)}`,
    `Configured production DB path: ${sanitizeRecoveryDatabasePathDisplay(config.configuredProductionDatabasePath)}`,
    `Recovery schema version: ${String(RW0_SCHEMA_VERSION)}`,
    'Production schema: untouched (must remain 9; migration 010 ABSENT)',
    `Watch cadence ms: ${String(RW0_WATCH_CADENCE_MS)}`,
    `Watch TTL ms: ${String(RW0_WATCH_TTL_MS)}`,
    `Cooldown ms: ${String(RW0_COOLDOWN_MS)}`,
    `Max concurrent high-res watch slots: ${String(RW0_MAX_CONCURRENT_WATCHES)}`,
    `Watch slot states: ${RW0_WATCH_SLOT_STATES.join(', ')}`,
    `Max episodes per mint per 24h: ${String(RW0_MAX_EPISODES_PER_MINT_PER_24H)}`,
    `Cost model: ${RW0_COST_MODEL}`,
    `Execution model: ${RW0_EXECUTION_MODEL}`,
    'Shadow research: SHADOW_RESEARCH_OPEN is the only simulation path (safety_incomplete, completeness FAIL, not live-readiness)',
    'Shadow exit/CLOSED: NOT IMPLEMENTED IN rw0_v1; SHADOW_RESEARCH_OPEN cannot CLOSED until a dedicated exit slice',
    'Recovery confirmation: legal only when recoveryConfirmedAt < watchStartedAt + 2h TTL; exact expiry belongs to EXPIRED',
    'Confirmation persist: derived from a stored rw0_market_observations row; caller economics cannot override',
    'Safety-approved paper: PAPER_ELIGIBLE / PAPER_OPEN names are reserved and unreachable in rw0_v1',
    'Manually setting holder/bundle/creator PASS cannot reach PAPER; that requires a new spec version and fingerprint',
    'Holder/bundle/creator evidence: UNKNOWN-only in rw0_v1 (PASS and FAIL rejected)',
    'Runtime RW0_DATABASE_PATH=:memory: REJECTED; :memory: is test-only via openRecoveryMemoryDatabase',
    'Holder gate: UNKNOWN (largest_real_holder_pct not implemented)',
    'Bundle gate: UNKNOWN (linked_bundle_pct not implemented)',
    'Creator gate: UNKNOWN',
    'Discovery coverage: INCOMPLETE (DexScreener latest profile/boost research collection only)',
    'Historical recovery_v0 sample used sparse ~5-minute observations; 60s confirmation is a new forward regime and historical percentages are not proof of that regime',
    'Network polling: NOT IMPLEMENTED IN THIS SLICE',
  ];
}
