export const SPL_TOKEN_PROGRAM_ID = 'TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA';
export const TOKEN_2022_PROGRAM_ID = 'TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb';
export const SYSTEM_PROGRAM_ID = '11111111111111111111111111111111';

export const CONCENTRATION_VERY_HIGH_TOP1_BPS = 5000;
export const CONCENTRATION_ELEVATED_TOP1_BPS = 2000;
export const CONCENTRATION_ELEVATED_TOP5_BPS = 5000;
export const MAX_LARGEST_ACCOUNTS = 20;
export const BASIS_POINTS_PER_UNIT = 10_000;

export const FINDING_CODES = {
  MINT_AUTHORITY_ACTIVE: 'MINT_AUTHORITY_ACTIVE',
  FREEZE_AUTHORITY_ACTIVE: 'FREEZE_AUTHORITY_ACTIVE',
  PERMANENT_DELEGATE_ACTIVE: 'PERMANENT_DELEGATE_ACTIVE',
  NON_TRANSFERABLE_TOKEN: 'NON_TRANSFERABLE_TOKEN',
  TRANSFER_HOOK_ACTIVE: 'TRANSFER_HOOK_ACTIVE',
  DEFAULT_ACCOUNT_STATE_FROZEN: 'DEFAULT_ACCOUNT_STATE_FROZEN',
  TRANSFER_FEE_CONFIGURED: 'TRANSFER_FEE_CONFIGURED',
  UNCLASSIFIED_TOKEN_EXTENSION_PRESENT: 'UNCLASSIFIED_TOKEN_EXTENSION_PRESENT',
  MINT_CLOSE_AUTHORITY_PRESENT: 'MINT_CLOSE_AUTHORITY_PRESENT',
  PAUSABLE_TOKEN_PAUSED: 'PAUSABLE_TOKEN_PAUSED',
  PAUSE_AUTHORITY_ACTIVE: 'PAUSE_AUTHORITY_ACTIVE',
  TOKEN_ACCOUNT_CONCENTRATION_VERY_HIGH: 'TOKEN_ACCOUNT_CONCENTRATION_VERY_HIGH',
  TOKEN_ACCOUNT_CONCENTRATION_ELEVATED: 'TOKEN_ACCOUNT_CONCENTRATION_ELEVATED',
  CONCENTRATION_DATA_INCONSISTENT: 'CONCENTRATION_DATA_INCONSISTENT',
} as const;
